class Add {
	static Nav() {
		return (
			"<nav class='navbar navbar-expand-lg navbar-dark bg-dark'> 				<div class='container'> 					<a class='navbar-brand' href='index.html'> 						<img src='img/logo.png' class='mr-4' width='100' height='50' alt='Logo' loading='lazy'> 					</a> 					<button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'> 						<span class='navbar-toggler-icon'></span> 					</button> 					<div class='collapse navbar-collapse' id='navbarSupportedContent'> 						<ul class='navbar-nav mr-auto'> 							<li class='nav-item'> 								<a class='nav-link' href='index.html'>Home</a> 							</li> 							<li class='nav-item'> 								<a class='nav-link' href='servicos.html'>Serviços</a> 							</li> 							</li> 							<li class='nav-item'> 								<a class='nav-link' href='duvidas.html'>Dúvidas</a> 							</li> 							<li class='nav-item'> 								<a class='nav-link' href='contato.html'>Contato</a> 							</li>					 						</ul> 					</div> 				</div> 			</nav>"
		);
	}
	static Footer() {
		return (
			"<footer class='page-footer font-small text-light bg-dark pt-4'> 					<div class='container pb-5'> 						<div class='row'> 							<div class='col-md-6'> 								<strong>Sobre a empresa:</strong> 								<p class='pt-2'> 									xxxxxx xxxxxxx xx xxxxxxx xx xxxxxxxxx xxxxxxxx  xxxxxxx xxxxxx xxxxx xxxxx xxxx xxxxxx xxxx 									xxxxxx xxxxxxx xx xxxxxxx xx xxxxxxxxx xxxxxxxx  xxxxxxx xxxxxx xxxxx xxxxx xxxx xxxxxx xxxx 									xxxxxx xxxxxxx xx xxxxxxx xx xxxxxxxxx xxxxxxxx  xxxxxxx xxxxxx xxxxx xxxxx xxxx xxxxxx xxxx 									xxxxxx xxxxxxx xx xxxxxxx xx xxxxxxxxx xxxxxxxx  xxxxxxx xxxxxx xxxxx xxxxx xxxx 								</p> 							</div> 							<div class='col-md-2'> 								<strong>Links:</strong> 								<ul class='list-unstyled pt-2 link_footer'> 									<li> 										<a class='text-decoration-none text-light' href='index.html'>Home</a> 									</li> 									<li> 										<a class='text-decoration-none text-light' href='servicos.html'>Serviços</a> 									</li> 									<li> 										<a class='text-decoration-none text-light' href='duvidas.html'>Dúvidas</a> 									</li> 									<li> 										<a class='text-decoration-none text-light' href='contato.html'>Contato</a> 									</li> 								</ul> 							</div> 							<div class='col-md-4'> 								<strong>Contato:</strong> 								<ul class='list-unstyled pt-2 link_footer'> 									<li> 										<img class='icones_footer' src='img/icones/endereco_white.svg' alt='endereco'></img> 										<a class='text-decoration-none text-light' target='_blank' href='https://goo.gl/maps/h9sQzaFXN3SAjrxMA'>Rua Laplace, 148 <br> Vila Suiça - Santo André/SP <br> CEP: 09131-130</a> 									</li> 									<li> 										<img class='icones_footer' src='img/icones/telefone_white.svg' alt='telefone'></img> 										<a class='text-decoration-none text-light' href='tel:11958379442'>(11) 95837-9442</a> 									</li> 									<li> 										<img class='icones_footer' src='img/icones/email_white.svg' alt='e-mail'></img> 										<a class='text-decoration-none text-light' href='mailto:luanluizlls@gmail.com?subject=Solicitar Serviço.'>luanluizlls@gmail.com</a> 									</li> 								</ul>		 							</div>			 						</div> 					</div> 				</footer>"
		);
	}
}

window.onload = function AtualizarPersonagem () {
	document.getElementById("nav").innerHTML = Add.Nav();
	document.getElementById("footer").innerHTML = Add.Footer();
}